spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:/home/ec2-user/wildBoard;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: 1226
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: debug
    
server:
  servlet:
    session:
      timeout: 1800
#  org.hibernate.type: trace